In [1]:
from sklearn.preprocessing import normalize
from sklearn.preprocessing import MinMaxScaler

In [3]:
import pandas as pd
import numpy as np

In [4]:
x = np.array([[-232, 0, 0.2, 4], 
              [84, 33332, -323, 0],
              [0.4, -7, 0, -100000]])

In [5]:
x

array([[-2.3200e+02,  0.0000e+00,  2.0000e-01,  4.0000e+00],
       [ 8.4000e+01,  3.3332e+04, -3.2300e+02,  0.0000e+00],
       [ 4.0000e-01, -7.0000e+00,  0.0000e+00, -1.0000e+05]])

In [6]:
x_normalize = normalize(x)

In [7]:
x_normalize

array([[-9.99851029e-01,  0.00000000e+00,  8.61940542e-04,
         1.72388108e-02],
       [ 2.51997449e-03,  9.99949877e-01, -9.68990190e-03,
         0.00000000e+00],
       [ 3.99999999e-06, -6.99999998e-05,  0.00000000e+00,
        -9.99999998e-01]])

In [8]:
scaler = MinMaxScaler()
x_minmax = scaler.fit_transform(x)

In [9]:
x_minmax

array([[0.00000000e+00, 2.09964306e-04, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 9.99960002e-01],
       [7.35443038e-01, 0.00000000e+00, 9.99381188e-01, 0.00000000e+00]])